### ISSUE TITLE
Documentation: tutorials

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#114]
I think there should be two Jou tutorials:
- One for people coming from high-level languages
- One for C programmers (very short, only explain the non-obvious differences)

**Comment by sumeshir26** [comment]
I would definitely benefit from the first, because my entire programming experience is Python and JavaScript

**Comment by littlewhitecloud** [comment]
I think add a tutorial is very important
I feel that I will benefit from both tutorialsBecause my programming experience is all Python & C/C++
jou is a good language beacause I hope to use language include python & C/C+'s syntax

**Comment by Akuli** [comment]
There is now a tutorial linked from README. Please create issues if anything is unclear, or there are typos etc :)
