### ISSUE TITLE
"jou --update" does not work on Windows 7

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#131]
This is because `jou --update` simply runs a PowerShell script, and Windows 7 comes with an ancient powershell version that doesn't even have Invoke-WebRequest.

I don't think this should be fixed in the near future. Maybe if some day, using libraries (e.g. HTTPS library, JSON library, zip library) will be easy in Jou, I can rewrite the update script in Jou.

**Comment by sumeshir26** [comment]
Nice

**Comment by Akuli** [comment]
Nobody uses windows 7 except me
