### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#150]
Often a bad idea, sometimes a good idea. Needed for `fprintf()`.

To make global variables stand out, I think I will add a `global` keyword that can be used like so

```python
global foo: int

def set_foo(value: int) -> void:
    foo = value

def get_foo() -> int:
    return foo
```

It should also be possible to declare a global variable that is defined elsewhere. For example, `stdlib/io.jou` could do:
```python
declare global stdin: FILE*
declare global stdout: FILE*
declare global stderr: FILE*
```

**Comment by littlewhitecloud** [comment]
throught the keyword can be "static"...
