### ISSUE TITLE
How to compile it on windows?

### ISSUE THREAD

**Issue by littlewhitecloud** [Akuli/jou#154]
I thought adding a wiki to briefly explain how variable types are implemented would be helpful for adding new types...
I tried add new types but I can only add a little piece...
And when I run the makefile It outputs error(The "Makefile" file's syntax doesn't support for Windows? It's for Linux?)
![image](https://user-images.githubusercontent.com/71159641/215393341-d4b1f728-6168-43a1-86a8-1901fc1a95a6.png)
### But my clang really exsit...
![image](https://user-images.githubusercontent.com/71159641/215393510-76821c18-7a98-4e62-a9f2-47278b0c77d4.png)
So how can compile jou on Windows? (My computer doesn't support WSL...)

_Originally posted by @littlewhitecloud in https://github.com/Akuli/jou/issues/151#issuecomment-1408017063_

**Comment by Akuli** [comment]
See CONTRIBUTING.md. There is instructions for using the CodeBlocks IDE.
