### ISSUE TITLE
latest version cannot work on windows?

### ISSUE THREAD

**Issue by littlewhitecloud** [Akuli/jou#165]
I am run my code, but it say:
![image](https://user-images.githubusercontent.com/71159641/215622326-d247a117-c27e-426f-903b-ed27f5a4b932.png)
```
'C:\Program' is not an internal or external command, nor is it a runnable program or batch files.
```
I was updated jou this morning...
And I setup the path too.
What's the wrong?

**Comment by Akuli** [comment]
This was broken in #148 which changes the way Jou works: now Jou compiles your programs into `.exe` files and runs them. This has a few advantages compared to how it worked before.

But apparently I didn't test that everything works, if you install Jou into a folder whose name contains a space, such as `C:\Program Files`. I will fix this now.

**Comment by Akuli** [comment]
Try updating Jou now.
