### ISSUE TITLE
Double arithmetic error

### ISSUE THREAD

**Issue by littlewhitecloud** [Akuli/jou#167]
Thanks for adding the "double" type.
Still my "math" lib's error, When I test my "fabs" command, it doesn't work well...
I write a test file:
```python
from "stdlib/io.jou" import printf
from "./math.jou" import abs, fabs

def main() -> int:
    foo = -1.1
    printf("%d", fabs(foo))
    return 0 
```
And the math.jou:
```python
def abs(n: int) -> int:
    if (n < 0):
        return -n

def fabs(n: double) -> double:
    if (n < 0):
        return -n
```
#### -1717986918
![image](https://user-images.githubusercontent.com/71159641/215642122-bb0443f5-8522-4603-bec5-da108dbd8dd5.png)

**Comment by littlewhitecloud** [comment]
And I changed my code:
```python
def fabs(n: double) -> double:
    if (n < 0):
        return -1 * n # Maybe -n doesn't right?
```
And I test again:
![image](https://user-images.githubusercontent.com/71159641/215642288-fb135163-af5f-4c39-8d9a-a32c5fa46e20.png)
![image](https://user-images.githubusercontent.com/71159641/215642291-0b8c0fad-c4f0-4953-8c1b-f657b761d832.png)
Still wrong...

**Comment by littlewhitecloud** [comment]
I changed my test number to "-1.0" and It output 0
![image](https://user-images.githubusercontent.com/71159641/215642556-781c91f8-1d00-4a58-b094-7f0726e904e4.png)

**Comment by littlewhitecloud** [comment]
In fact, negative is positive（--1 = +1）

**Comment by Akuli** [comment]
You need to use `%f` instead of `%d` when printing doubles (just like in C).

**Comment by littlewhitecloud** [comment]
okay, let me try

**Comment by littlewhitecloud** [comment]
thanks
