### ISSUE TITLE
Can jou support Scientific notation?

### ISSUE THREAD

**Issue by littlewhitecloud** [Akuli/jou#169]
like:
```python
eps = 1e-7
```

**Comment by Akuli** [comment]
We can add support for this. Not sure if llvm can simply take a string like `"1e-7"` or do we need to compute the value, the documentation doesn't tell: https://llvm.org/doxygen/group__LLVMCCoreValueConstantScalar.html#gaa0e9de3c235f88f2622a88fdd090fe66
