### ISSUE TITLE
Should jou have a math lib?

### ISSUE THREAD

**Issue by littlewhitecloud** [Akuli/jou#204]
python, c, c++ have math lib...
```python
# python
import math
```
```c
// C
#include <math.h>
```
```c++
// Cplusplus
#include <cmath>
```
So, does jou need a mathlib in future?
```python
# Jou
from ".../math.jou" import ...
```

**Comment by Akuli** [comment]
Yes, it would be good to have a math lib. We can probably just `declare` existing C functions similarly to how the existing stdlibs work.

**Comment by littlewhitecloud** [comment]
how to use the ```declare``` keyword?

**Comment by Akuli** [comment]
The `declare` keyword makes an existing C function available in Jou code.

For example, consider the `abs()` functions. In C they are:

```c
       int abs(int j);
       long labs(long j);
       long long llabs(long long j);
```

C's `long` is 32-bit on Windows and 64-bit on Linux, but C's `int` is always* 32 bits (Jou `int`) and C's `long long` is always* 64 bits (Jou `long`). So in jou you can do:

```
from "stdlib/io.jou" import printf

declare abs(j: int) -> int
declare llabs(j: long) -> long

def main() -> int:
    printf("%d\n", abs(-6))
    printf("%lld\n", llabs(-6L))
    return 0
```

Here `declare abs(j: int) -> int` tells the compiler that there exists a function `abs` taking an `int` argument and returning `int`, just like the C code `int abs(int j);` does. The names of the arguments don't need to match their names in C, but the types must match.

**Comment by littlewhitecloud** [comment]
oh, thank you very much declare is a very good idea!

**Comment by littlewhitecloud** [comment]
Improved in Math lib pr

**Comment by Akuli** [comment]
It's been a couple years, and I really like the math lib, I've used it in many advent of code solutions, and now even the Jou compiler uses it.

Thanks for math lib and all your other work on Jou! :)
