### ISSUE TITLE
import all functions from file

### ISSUE THREAD

**Issue by littlewhitecloud** [Akuli/jou#215]
How to import all functions from file? (I an writing math lib test for jou)
Or, jou doesn't support it yet?

**Comment by Akuli** [comment]
Not supported, but you can put imports on separate lines with parentheses. See `tests/should_succeed/file.jou` for an example:

https://github.com/Akuli/jou/blob/ef849db4398bc1fc68bc1be549899ec2f80bea4d/tests/should_succeed/file.jou#L1-L6

**Comment by littlewhitecloud** [comment]
oh, okay

**Comment by littlewhitecloud** [comment]
throught can add syntax like:
```python
from "{file_name}" import * # Improt all functions in {file_name}
```

**Comment by Akuli** [comment]
After thinking about this a bit more, I think this should be the *only* way to import Jou files:
- In a language like Python, the advantage of `from os import system` syntax is that if another file/module also has a function named `system` (e.g. Python's `platform` module), it won't conflict with what you imported. But in Jou it would: the linker will complain if two files define two different functions with the same name.
- Currently you need to list all the function names you use. Getting compiler errors/warnings when the list gets outdated is also annoying.

The main disadvantages in the `import *` approach is that it's harder to see what file defines a function. But naming helps: `strlen` comes from `str.jou`.

And for people who dislike C's `#include`: Jou's `import *` is still going to be better than C's `#include`.
- You don't need header guards.
- Cyclic imports "just work".
- The compiler can automatically detect which imports were unused and show warnings for them. In C this requires a separate tool called IWYU (Include-What-You-Use) that usually takes a couple hours to configure for your project.
