### ISSUE TITLE
Large programs compile really slowly without optimizations

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#236]
`jou -O1 self_hosted/tokenizer.jou` takes a couple seconds to compile

`jou self_hosted/tokenizer.jou` seems to be taking just about forever. After about 30 seconds of waiting, it was still going, and I didn't feel like measuring how long it takes :)

I have debugged this a bit: The generated LLVM IR is ridiculously large, and writing it all into a huge object file takes some time. It is faster to tell LLVM to optimize it first, which makes it a lot smaller.

**Comment by littlewhitecloud** [comment]
Maybe can set jou default optimize to "O1"?

**Comment by littlewhitecloud** [comment]
Or add a check for big file, and auto set the optimize to "O1" if there's no optimize flag.

**Comment by littlewhitecloud** [comment]
Feel set default optimize to "O0" isn't a good idea...

**Comment by Akuli** [comment]
No longer a problem, because we use -O1 by default.
