### ISSUE TITLE
__init__ doesn't work

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#249]
The `__init__` method doesn't have a special meaning in Jou, but people coming from Python probably expect it to have a special meaning.

```
from "stdlib/io.jou" import printf

struct Foo:
    def __init__(self: Foo) -> void:
        printf("Hello!!!!\n")

def main() -> int:
    x = Foo{}
    return 0
```

Expected result: an error saying that `__init__` does not work like in Python

Actual result: no error

**Comment by littlewhitecloud** [comment]
I think maybe we can add some methods to the class like __init__

**Comment by Akuli** [comment]
Indeed: I want to keep Jou simple again. The compiler should give an error message for this though, so that you know `__init__` doesn't work like in Python.

I realize I'm saying "no" to many things you suggest. It is because I have seen many other languages that start off like "it's just C with classes", but after a while they become so large that they don't feel like C at all.

**Comment by littlewhitecloud** [comment]
I see. Jou is a simple language not a large one.
