### ISSUE TITLE
Rename struct to class?

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#252]
Advantages:
- Feels like it makes more sense now that `struct` can have methods in it
- Consistent with Python
- Would syntax highlight better when abusing Python syntax highlighting for Jou programs

Disadvantages:
- Somehow "a class" doesn't feel like it emphasizes how it's just a way to arrange bytes in memory
- Could seem disgusting to C programmers who associate classes with other garbage that OOP people do

**Comment by littlewhitecloud** [comment]
Sounds like ... a good idea?

**Comment by littlewhitecloud** [comment]
If struct has __init__ (#249) I will rename ```struct``` to ```class```
