### ISSUE TITLE
Warning: compare_compilers.sh will generate "NUL" file and it can't be delete

### ISSUE THREAD

**Issue by littlewhitecloud** [Akuli/jou#300]
Because #292, I am testing compare_compilers.sh
And it can't compile...
![image](https://user-images.githubusercontent.com/71159641/222940071-653d4df2-4297-47f1-8fd4-29c46b6fa4c8.png)
But when I try to delete test folder, it say:
The MS-DOS function is invalid
I find there is a new file in my test folder, it is "NUL".
![image](https://user-images.githubusercontent.com/71159641/222940040-1a13894f-b121-479a-9ec1-2a9a4869e445.png)
What happened to it?

**Comment by Akuli** [comment]
To get rid of the `NUL` file, try changing `NUL` to `/dev/null` in `Makefile.windows`.

You should have a `mingw64` *folder*, not a zip file. Did the `./windows_setup.sh` script fail mid-way when running? What is the output you get from `./windows_setup.sh`?

**Comment by Akuli** [comment]
You might be able to delete the `NUL` file by running `rm NUL` in git bash.
