### ISSUE TITLE
&&,|| error messages

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#301]
Jou uses `and`, `or` instead of  `&&`, `||` . It would be nice if you got a good error message saying e.g. `use 'and' instead of '&&'` if you accidentally use `&&`.

**Comment by littlewhitecloud** [comment]
Think we can support it and just give user a warning message: ```use 'expr' instead of 'expr' ```

**Comment by Akuli** [comment]
I don't think it's a good idea to have two ways to do the same thing, especially if one of the two is always worse. So it should be an error, not a warning.
