### ISSUE TITLE
Why we need windows_setup.sh now?

### ISSUE THREAD

**Issue by littlewhitecloud** [Akuli/jou#310]
Run jou on windows doesn't need windows_setup.sh before.
![image](https://user-images.githubusercontent.com/71159641/223709383-b20b16d0-0d43-43af-a7fa-e2302f08b7ee.png)
And it takes me a long time to download mingw64...

**Comment by littlewhitecloud** [comment]
lol, I am looking forward to downloading the mingw doesn't take 4 hours.

**Comment by Akuli** [comment]
Thanks for still working on Jou despite always having some annoying issue :)
