### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by littlewhitecloud** [Akuli/jou#342]
![image](https://user-images.githubusercontent.com/71159641/226065723-e2a3fbc9-66b1-4fd6-8c64-bc2317161302.png)
```
compiler error in file "self_hosted/create_llvm_ir.jou", line 573: method do_pass() takes 0 arguments, but it was called with 0 arguments
mingw32-make: *** [Makefile.windows:34: self_hosted_compiler.exe] Error 1

**Comment by Akuli** [comment]
Duplicate of #275. You most likely forgot to use `self` when defining the method: `def do_pass()` should be `def do_pass(self)`.

**Comment by Akuli** [comment]
Also, I'm glad you're finally able to work on the self-hosted compiler now! :tada: Sorry that it took so long for me to make something that actually works for you.

**Comment by littlewhitecloud** [comment]
thx
