### ISSUE TITLE
Output Chinese characters generate garbled characters

### ISSUE THREAD

**Issue by littlewhitecloud** [Akuli/jou#392]
![image](https://github.com/Akuli/jou/assets/71159641/0a7f4a27-090a-4b1d-b451-062899a7cb1e)
I want:
```
你好，世界
```
Result:
```
浣犲ソ锛屼笘鐣
```
Is there something wrong with encoding settings?
code:
```python
import "stdlib/io.jou"

def main() -> int:
    printf("%s", "你好，世界")
    return 0
```

**Comment by littlewhitecloud** [comment]
![image](https://github.com/Akuli/jou/assets/71159641/6e89fd0f-7d4a-4deb-ab89-7fdbf00b8c01)
successed in cplusplus with printf, but failed in jou with printf

**Comment by littlewhitecloud** [comment]
![image](https://github.com/Akuli/jou/assets/71159641/d0f2cea3-74f5-415e-904d-7971acad0016)

**Comment by Akuli** [comment]
Encodings are really hard to get right on Windows. I haven't put any effort into that with Jou. For now you could try different terminals (cmd.exe, git bash, powershell).

**Comment by littlewhitecloud** [comment]
I just found the solution: chcp 65001

**Comment by littlewhitecloud** [comment]
python can use #encoding:gbk to fix it maybe we can add it
(Actually I really want to make a llvm version “Python” because it is really slow.)
