### ISSUE TITLE
jou_compiled gitignore

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#397]
Would be nice if `jou_compiled/.gitignore` was auto-generated and it ignored everything. This is super easy to generate, too. The file should just contain a single character `*`.

Other tools with output folders do this already, e.g. `wasm-pack`.

**Comment by Akuli** [comment]
@littlewhitecloud interested in working on this? Creating a single-character file should be super easy :)

**Comment by littlewhitecloud** [comment]
You mean generate `.gitignore` in the `jou_complied` folder and write in `*` to avoid upload all of the `.obj` file?

**Comment by littlewhitecloud** [comment]
LOL I will take time to do it but I just bought a new computer and Windows 11 really different from Windows 10. I need time to build the env.
