### ISSUE TITLE
None return

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#423]
Python typing uses `-> None` when there is no return value, Jou uses `-> void`.

Jou should switch to `-> None`, or at least display a good error message if someone uses `-> None`.

**Comment by Akuli** [comment]
We will need the `void` keyword anyway for void pointers. Will it be confusing if the same code uses both `void` and `None`?

```python
declare free(ptr: void*) -> None
```

@littlewhitecloud I want to know what you think. Should Jou use `-> void` (similar to C) or `-> None` (similar to Python) when function does not return a value?

**Comment by Moosems** [comment]
Is there an internal difference between `void` and `None`?

**Comment by littlewhitecloud** [comment]
I am sorry I came later, I think jou should use `-> None` and Akuli already wrote it.
