### ISSUE TITLE
bool == bool

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#477]
The `==` and `!=` operators cannot be used with bools. Creates error like this:

```
compiler error in file "bigint.jou", line 147: wrong types: cannot compare bool and bool
```

**Comment by Akuli** [comment]
Not sure if this is a feature or a bug. Many people end up writing `if foo == False`, which is just almost always less readable than `if not foo`. So providing no `==` and `!=` operators might be helpful.

But on the other hand, consider these:

```python
if (foo and bar) or (not foo and not bar):
    ...
if (foo and not bar) or (bar and not foo):
    ...
```

They would be more readable like this:

```python3
if foo == bar:
    ...
if foo != bar:
    ...
```

@Moosems and @littlewhitecloud, what do you think?

**Comment by Moosems** [comment]
I'd say it's a good thing to have. If you don't like those specific signs, you could make a new comparative keyword for this 🤷‍♂️.
