### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by sumeshir26** [Akuli/jou#78]
Really excited to try this

**Comment by sumeshir26** [comment]
> Awesome! I now wonder how you found this project :)

Well, I started following you after seeing Porcupine, and here I am :)

> If you are stuck on Windows, you can use WSL for now. It is basically the Linux terminal but inside Windows.

Gonna try that, thanks!

**Comment by sumeshir26** [comment]
I tried one of your examples:
![image](https://user-images.githubusercontent.com/68823982/213424027-4900ff5b-56b9-4a58-9546-7ee05ce93908.png)
And this occurred:
![image](https://user-images.githubusercontent.com/68823982/213424099-fb6e2cf0-246f-4e24-9d57-0f994f36bbcf.png)

**Comment by Akuli** [comment]
First screenshot: vscode uses pylance, because it is convinced that `test.jou` is a Python file. Maybe there is a way to disable pylance for `.jou` files, but leave it enabled for actual Python files?

Second screenshot: You need to run `test.jou` with the Jou interpreter `./jou`. For example, `./jou test.jou`. The commands to compile it are in the README. You are trying to run it with bash (maybe with `. test.jou` or `./test.jou` or `bash test.jou`).

**Comment by sumeshir26** [comment]
> First screenshot: vscode uses pylance, because it is convinced that `test.jou` is a Python file. Maybe there is a way to disable pylance for `.jou` files, but leave it enabled for actual Python files?
> 
> Second screenshot: You need to run `test.jou` with the Jou interpreter `./jou`. For example, `./jou test.jou`. The commands to compile it are in the README. You are trying to run it with bash (maybe with `. test.jou` or `./test.jou` or `bash test.jou`).

Okay, thanks so much!

**Comment by Akuli** [comment]
Let me know if you need more help or if you manage to run some Jou code :)

**Comment by sumeshir26** [comment]
What are the problems with supporting Jou on windows? C and H are cross-platform right?

**Comment by Akuli** [comment]
The biggest issue is getting a C compiler installed. Installing a C compiler on Windows is possible, but last time I tried, I spent a few days on it and gave up. Maybe you'll have better luck. If you decide to try this, try installing the `clang` compiler, becuse it is what I use to develop Jou on Linux.

That's the hard part. Everything below is details that I'm sure we will figure out if we get a C compiler to work on Windows.

To invoke `clang`, there is currently a `Makefile`, a configuration file that contains commands that the `make` program runs. My impression is that Windows doesn't really have anything similar to `make`, and many projects instead use a huge and annoying framework like `cmake` (not to be confused with `make`), or just do whatever their IDE likes to do (e.g. cpython has a bunch of visual studio project files).

The Jou compiler also uses a few functions that aren't available on Windows, such as `dirname()`, but making it cross-platform should be easy.

Jou's tests are written as a bash script. I could probably rewrite the test script in C.

Jou's tests use `valgrind`, a tool that doesn't work on Windows. However, it is already possible to run the tests without valgrind, so this shouldn't be a problem.

**Comment by Akuli** [comment]
I actually managed to get a C compiler to work on Windows. Maybe there will be Windows support within the next few days/weeks :)

**Comment by Akuli** [comment]
I managed to run some Jou programs on windows, without using WSL. My work so far is in #103. Tomorrow I will rewrite my notes into some instructions you can follow :)

**Comment by Akuli** [comment]
(closed accidentally)
