### ISSUE TITLE
Same function defined in two different files

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#85]
```python
# foo1.jou
def foo() -> int:
    return 1

# foo2.jou
def foo() -> int:
    return 2

# foo2_wrapper.jou
from foo2 import foo
def wrapped_foo() -> int:
    return foo()

# main.jou
from "stdlib/io.jou" import printf
from "./foo1.jou" import foo
from "./foo2.jou" import wrapped_foo
def main() -> int:
    printf("%d %d\n", foo(), wrapped_foo())
```

IMO this should be a linker error. Each file by itself should compile fine, because the name `foo` is not used twice within the same file, but the linker still has to deal with two functions named `foo`.

I haven't tried what this does currently.

**Comment by littlewhitecloud** [comment]
You can try function overloading...? 
Oh, no your program doesn't have different variable to overload

**Comment by littlewhitecloud** [comment]
Oh, you can try Name modification to recognition two different functions

**Comment by littlewhitecloud** [comment]
C++ used name decoration for example:
```cplusplus
long MyFunctionFoo(int, float)
```
Name decoration in compiler:
?MyFunctionFoo@@YAXH
And you can custom your name decoration and the program will recognition two different functions...

**Comment by littlewhitecloud** [comment]
Wait, did you include correctly? 
Doesn't it include "./foo2_warpper.jou"??????? why "./foo2.jou"
foo2.jou doesn't include wrapped_foo

**Comment by Akuli** [comment]
With small syntax changes and typo fixes, this is a linker error.

```
akuli@akuli-desktop:~/jou/a$ ../jou main.jou 
/usr/bin/ld: ./jou_compiled/main/foo1.o: in function `foo':
foo1.jou:(.text+0x0): multiple definition of `foo'; ./jou_compiled/main/foo2.o:foo2.jou:(.text+0x0): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
